#!/bin/bash

function rutorrent_install() {
    apt_install sox geoip-database p7zip-full zip unzip php-bcmath

    mkdir -p /srv
    if [[ ! -d /srv/rutorrent ]]; then
        echo_progress_start "Cloning ruTorrent"
        # Get current stable ruTorrent version
        release=$(git ls-remote --tags --refs https://github.com/novik/ruTorrent.git | awk '{sub("refs/tags/", ""); print $2 }' | grep -v beta | sort -Vr | head -n1)
        git clone --recurse-submodules --depth 1 -b ${release} https://github.com/Novik/ruTorrent.git /srv/rutorrent >> "$log" 2>&1 || {
            echo_error "Failed to clone ruTorrent"
            exit 1
        }
        chown -R www-data:www-data /srv/rutorrent
        rm -rf /srv/rutorrent/plugins/throttle
        rm -rf /srv/rutorrent/plugins/_cloudflare
        rm -rf /srv/rutorrent/plugins/dump
        rm -rf /srv/rutorrent/plugins/extratio
        rm -rf /srv/rutorrent/plugins/rpc
        rm -rf /srv/rutorrent/plugins/geoip
        rm -rf /srv/rutorrent/conf/config.php
        echo_progress_done "ruTorrent cloned"
    fi

    echo_progress_start "Cloning some popular themes and plugins"
    sed -i 's/useExternal = false;/useExternal = "mktorrent";/' /srv/rutorrent/plugins/create/conf.php
    sed -i 's/pathToCreatetorrent = '\''\''/pathToCreatetorrent = '\''\/usr\/bin\/mktorrent'\''' /srv/rutorrent/plugins/create/conf.php
    sed -i "s/\$pathToExternals\['sox'\] = ''/\$pathToExternals\['sox'\] = '\/usr\/bin\/sox'/g" /srv/rutorrent/plugins/spectrogram/conf.php

    . /etc/swizzin/sources/functions/utils
    install_rar

    if [[ ! -d /srv/rutorrent/plugins/filemanager ]]; then
        git clone https://github.com/nelu/rutorrent-filemanager /srv/rutorrent/plugins/filemanager >> ${log} 2>&1 || {
            echo_error "git of file-manager plugin to main plugins seems to have failed"
        }
        rutorrent_fm_config
    fi

    if [[ ! -d /srv/rutorrent/plugins/ratiocolor ]]; then
        git clone https://github.com/Gyran/rutorrent-ratiocolor /srv/rutorrent/plugins/ratiocolor >> "$log" 2>&1
        sed -i "s/changeWhat = \"cell-background\";/changeWhat = \"font\";/g" /srv/rutorrent/plugins/ratiocolor/init.js || {
            echo_error "git of ratio plugin to main plugins seems to have failed"
        }
    fi

    if [[ ! -d /srv/rutorrent/plugins/geoip2 ]]; then
        git clone https://github.com/Micdu70/geoip2-rutorrent /srv/rutorrent/plugins/geoip2 >> ${log} 2>&1 || {
            echo_error "git of geoip2 plugin to main plugins seems to have failed"
        }
    fi

    echo_progress_done "Plugins downloaded"

    if [[ -f /install/.quota.lock ]] && [[ -z $(grep quota /srv/rutorrent/plugins/diskspace/action.php) ]]; then
        rutorrent_fix_quota
    fi

    cat > /srv/rutorrent/conf/config.php << 'RUC'
<?php
	// configuration parameters

	// for snoopy client
	$httpUserAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36';
	$httpTimeOut = 30; // in seconds
	$httpUseGzip = true;
	$httpIP = null;
	$httpProxy = array
	(
		'use' 	=> false,
		'proto'	=> 'http',
		'host'	=> 'PROXY_HOST_HERE',
		'port'	=> 3128
	);

	$rpcTimeOut = 5;
	$rpcLogCalls = false;
	$rpcLogFaults = true;

	$phpUseGzip = false;
	$phpGzipLevel = 2;

	$schedule_rand = 10;

	$do_diagnostic = true;
	$al_diagnostic = true;
	$log_file = '/tmp/errors.log';
	$saveUploadedTorrents = true;
	$overwriteUploadedTorrents = false;

	$forbidUserSettings = false;

	$throttleMaxSpeed = 327625*1024;

	$pathToExternals = array(
		"php" 	=> '',
		"curl"	=> '',
		"gzip"	=> '',
		"id"	=> '',
		"stat"	=> '',
	);

	$localHostedMode = true;
	$cachedPluginLoading = false;

	$localhosts = array(
		"127.0.0.1",
		"localhost",
	);

	$profilePath = '../../share';
	$profileMask = 0777;

	$tempDirectory = null;

	$canUseXSendFile = false;

	$locale = "UTF8";

	$enableCSRFCheck = false;
	$enabledOrigins = array();
RUC
}

function rutorrent_fm_config() {
    if [[ "$(_os_arch)" = "arm64" ]]; then
        cat > /srv/rutorrent/plugins/filemanager/conf.php << 'RUFMC'
<?php

    global $pathToExternals;
    $pathToExternals['7zip'] = '/usr/bin/7z';

    $config['mkdperm'] = 755;
    $config['show_fullpaths'] = false;

    $config['textExtensions'] = 'log|txt|nfo|sfv|xml|html';

    $config['fileExtractExtensions'] = '(7z|bzip2|t?bz2|tgz|gz(ip)?|iso|img|lzma|rar|tar|t?xz|zip|z01|wim)(\.[0-9]+)?';

    $config['archive']['type'] = [
        '7z' => [
            'bin' => '7zip',
            'compression' => [1, 5, 9],
        ]];

   $config['archive']['type']['zip'] = $config['archive']['type']['7z'];
   $config['archive']['type']['tar'] = $config['archive']['type']['7z'];
   $config['archive']['type']['tar']['has_password'] = false;
   $config['archive']['type']['bz2'] = $config['archive']['type']['tar'];
   $config['archive']['type']['gz'] = $config['archive']['type']['tar'];
   $config['archive']['type']['tar.7z'] = $config['archive']['type']['tar'];
   $config['archive']['type']['tar.bz2'] = $config['archive']['type']['tar'];
   $config['archive']['type']['tar.gz'] = $config['archive']['type']['tar'];
   $config['archive']['type']['tar.xz'] = $config['archive']['type']['tar'];

   $config['archive']['type']['tar.gz']['multipass'] = ['tar', 'gzip'];
   $config['archive']['type']['tar.bz2']['multipass'] = ['tar', 'bzip2'];
   $config['archive']['type']['tar.7z']['multipass'] = ['tar', '7z'];
   $config['archive']['type']['tar.xz']['multipass'] = ['tar', 'xz'];
RUFMC
    fi
}

function rutorrent_nginx_config() {
    if [[ ! -f /etc/nginx/apps/rutorrent.conf ]]; then
        phpversion=$(php_service_version)
        sock="php${phpversion}-fpm"
        if [[ -f /install/.authelia.lock ]]; then
            cat > /etc/nginx/apps/rutorrent.conf << RUM
location /rutorrent {
    auth_request /_authz;
    auth_request_set \$authelia_user \$upstream_http_remote_user;
    auth_request_set \$authelia_redirect \$upstream_http_location;
    error_page 401 = @authelia_redirect;

    location ~ \.php\$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)\$;
        fastcgi_pass unix:/run/php/${sock}.sock;
        fastcgi_param SCRIPT_FILENAME \$request_filename;
        fastcgi_param REMOTE_USER \$authelia_user;
        include fastcgi_params;
        fastcgi_index index.php;
    }
}
RUM
        else
            cat > /etc/nginx/apps/rutorrent.conf << RUM
location /rutorrent {
  auth_basic "What's the password?";
  auth_basic_user_file /etc/htpasswd;

  location ~ \.php\$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)\$;
    fastcgi_pass unix:/run/php/${sock}.sock;
    fastcgi_param SCRIPT_FILENAME \$request_filename;
    include fastcgi_params;
    fastcgi_index index.php;
  }
}
RUM
        fi
    fi

    if [[ ! -f /etc/nginx/apps/rindex.conf ]]; then
        cat > /etc/nginx/apps/rindex.conf << RIN
location /rtorrent.downloads {
  alias /home/\$remote_user/torrents/rtorrent;
  include /etc/nginx/snippets/fancyindex.conf;
  auth_basic "What's the password?";
  auth_basic_user_file /etc/htpasswd;
  
  location ~* \.php($|/) {

  } 
}
RIN
    fi
}

function rutorrent_user_config() {
    users=($(_get_user_list))
    for user in "${users[@]}"; do
        if [[ ! -f /srv/rutorrent/conf/users/${user}/config.php ]]; then
            mkdir -p /srv/rutorrent/conf/users/${user}/
            cat > /srv/rutorrent/conf/users/${user}/config.php << RUU
<?php
\$topDirectory = '/home/${user}';
\$scgi_port = 0;
\$scgi_host = "unix:///var/run/${user}/.rtorrent.sock";
\$XMLRPCMountPoint = "/${user}";
\$quotaUser = "${user}";
?>
RUU
        fi

        if [[ ! -f /etc/nginx/apps/${user}.scgi.conf ]]; then
            cat > /etc/nginx/apps/${user}.scgi.conf << RUC
location /${user} {
include scgi_params;
scgi_pass unix:/var/run/${user}/.rtorrent.sock;
auth_basic "What's the password?";
auth_basic_user_file /etc/htpasswd.d/htpasswd.${user};
}
RUC
        fi
    done
}

function rutorrent_fix_quota() {
    cat > /srv/rutorrent/plugins/diskspace/action.php << 'DSKSP'
<?php
#################################################################################
##  [Quick Box - action.php modified for quota systems use]
#################################################################################
  require_once( '../../php/util.php' );
  if (isset($quotaUser) && file_exists('/install/.quota.lock')) {
    $total = shell_exec("sudo /usr/bin/quota -wu ".$quotaUser."| tail -n 1 | sed -e 's|^[ \t]*||' | awk '{print $3*1024}'");
    $used = shell_exec("sudo /usr/bin/quota -wu ".$quotaUser."| tail -n 1 | sed -e 's|^[ \t]*||' | awk '{print $2*1024}'");
    $free = sprintf($total - $used);
    CachedEcho::send('{ "total": '.$total.', "free": '.$free.' }',"application/json");
  } else {
      CachedEcho::send('{ "total": '.disk_total_space($topDirectory).', "free": '.disk_free_space($topDirectory).' }',"application/json");
  }
?>
DSKSP
}